DROP TABLE IF EXISTS TB_HEROIS;

CREATE TABLE TB_HEROIS (
  ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
  NOME TEXT NOT NULL,
  PODER TEXT NOT NULL,
);

-- CREATE A HEROE
INSERT INTO TB_HEROIS (NOME, PODER) VALUES ('FLASH', 'VELOCIDADE'), ('AQUAMAN', 'FALAR COM OS ANIMAIS');

-- READ A HEROE OR ALL HEROES
SELECT * FROM TB_HEROIS;
SELECT * FROM TB_HEROIS WHERE NOME = 'FLASH';

-- UPDATE A HEROE
UPDATE TB_HEROIS SET NOME = 'GOKU', PODER = 'DEUS' WHERE ID = 1;

-- DELETE A HEROE
DELETE FROM TB_HEROIS WHERE ID = 2;